import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.SUPABASE_URL!;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

// Use anon client for auth operations
const supabase = createClient(supabaseUrl, supabaseAnonKey);
// Use service client for database operations
const supabaseService = createClient(supabaseUrl, supabaseServiceKey);

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const authHeader = request.headers.get('authorization');
    
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return NextResponse.json(
        { error: 'Authorization header required' },
        { status: 401 }
      );
    }

    const token = authHeader.split(' ')[1];

    // Verify the token and get user
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);
    
    if (authError || !user) {
      return NextResponse.json(
        { error: 'Invalid token' },
        { status: 401 }
      );
    }

    console.log('📄 Generating GP PDF for user:', user.email);

    const {
      appointmentReason,
      doctorUnderstanding,
      medicationsTried,
      recentTests,
      relevantSymptoms
    } = body;

    // Get user's symptom logs for the report
    const { data: symptomLogs, error: fetchError } = await supabaseService
      .from('symptom_logs')
      .select('*')
      .eq('user_id', user.id)
      .order('created_at', { ascending: false })
      .limit(20);

    if (fetchError) {
      console.error('❌ Error fetching symptom logs for PDF:', fetchError);
      return NextResponse.json(
        { error: 'Failed to fetch symptom data for PDF' },
        { status: 500 }
      );
    }

    // Generate PDF content
    const pdfContent = generatePDFContent({
      user,
      appointmentReason,
      doctorUnderstanding,
      medicationsTried,
      recentTests,
      relevantSymptoms,
      symptomLogs: symptomLogs || []
    });

    console.log('✅ PDF content generated successfully');

    return NextResponse.json({
      pdfContent,
      message: 'PDF content generated successfully'
    });

  } catch (error) {
    console.error('❌ Error in PDF generation API:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

interface PDFData {
  user: any;
  appointmentReason: string;
  doctorUnderstanding: string;
  medicationsTried: string;
  recentTests: string;
  relevantSymptoms: string[];
  symptomLogs: any[];
}

function generatePDFContent(data: PDFData) {
  const { user, appointmentReason, doctorUnderstanding, medicationsTried, recentTests, relevantSymptoms, symptomLogs } = data;
  
  const now = new Date();
  const formattedDate = now.toLocaleDateString('en-GB', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric'
  });

  let content = `# GP Appointment Report\n\n`;
  content += `**Generated:** ${formattedDate}\n`;
  content += `**Patient:** ${user.email}\n\n`;
  
  content += `## Appointment Context\n\n`;
  content += `**Reason for Appointment:**\n${appointmentReason}\n\n`;
  content += `**What you want the doctor to understand:**\n${doctorUnderstanding}\n\n`;
  content += `**Medications or remedies tried:**\n${medicationsTried}\n\n`;
  content += `**Recent tests or investigations:**\n${recentTests}\n\n`;
  
  content += `## Relevant Symptom History\n\n`;
  
  if (symptomLogs.length > 0) {
    const relevantLogs = relevantSymptoms.length > 0 
      ? symptomLogs.filter(log => 
          relevantSymptoms.some(symptom => 
            log.symptom_description.toLowerCase().includes(symptom.toLowerCase())
          )
        )
      : symptomLogs.slice(0, 5); // Show 5 most recent if no specific symptoms selected

    relevantLogs.forEach((log, index) => {
      const logDate = new Date(log.created_at).toLocaleDateString('en-GB');
      content += `### ${index + 1}. ${log.symptom_description}\n`;
      content += `**Date:** ${logDate}\n`;
      content += `**Severity:** ${log.severity}\n`;
      content += `**Duration:** ${log.duration}\n`;
      if (log.location) content += `**Location:** ${log.location}\n`;
      if (log.triggers && log.triggers !== 'None') content += `**Triggers:** ${log.triggers}\n`;
      if (log.notes) content += `**Notes:** ${log.notes}\n`;
      content += `\n`;
    });
  } else {
    content += `No symptom logs found.\n\n`;
  }
  
  content += `## Summary\n\n`;
  content += `This report was generated by Sympli Health Companion to assist with your GP appointment. `;
  content += `The information provided is based on your symptom logs and appointment context. `;
  content += `Please review and confirm all details with your healthcare provider.\n\n`;
  
  content += `**Total symptom logs:** ${symptomLogs.length}\n`;
  content += `**Relevant symptoms included:** ${relevantLogs?.length || 0}\n`;
  
  return content;
}
