import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { symptomData, socratesData } = body;

    const reportContent = generateSymptomReport(symptomData, socratesData);

    return NextResponse.json({
      reportContent
    });

  } catch (error) {
    console.error('❌ Error in generate report API:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

function generateSymptomReport(symptomData: any, socratesData: any): string {
  const now = new Date();
  const formattedDate = now.toLocaleDateString('en-GB', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  let report = `SYMPTOM REPORT\n`;
  report += `Generated: ${formattedDate}\n`;
  report += `=====================================\n\n`;

  // Basic symptom information
  report += `PRIMARY SYMPTOM\n`;
  report += `Symptom: ${symptomData.symptom}\n`;
  report += `Type: ${symptomData.type === 'new' ? 'New Symptom' : 'Ongoing Symptom'}\n`;
  if (symptomData.description) {
    report += `Description: ${symptomData.description}\n`;
  }
  report += `\n`;

  // Socrates assessment
  report += `DETAILED ASSESSMENT (SOCRATES)\n`;
  report += `Site: ${socratesData.site || 'Not specified'}\n`;
  report += `Onset: ${socratesData.onset || 'Not specified'}\n`;
  report += `Character: ${socratesData.character || 'Not specified'}\n`;
  report += `Radiation: ${socratesData.radiation || 'Not specified'}\n`;
  report += `Associations: ${socratesData.associations || 'Not specified'}\n`;
  report += `Time Course: ${socratesData.timeCourse || 'Not specified'}\n`;
  report += `Exacerbating Factors: ${socratesData.exacerbatingFactors || 'Not specified'}\n`;
  report += `Severity: ${socratesData.severity || 'Not specified'}/10\n`;
  report += `\n`;

  // Additional context
  if (socratesData.additionalContext) {
    report += `ADDITIONAL CONTEXT\n`;
    report += `${socratesData.additionalContext}\n`;
    report += `\n`;
  }

  // Clinical summary
  report += `CLINICAL SUMMARY\n`;
  report += `This ${symptomData.type} symptom of ${symptomData.symptom} was reported with a severity of ${socratesData.severity || 'unknown'}/10. `;
  
  if (socratesData.onset) {
    report += `The symptom began ${socratesData.onset}. `;
  }
  
  if (socratesData.character) {
    report += `It is described as ${socratesData.character}. `;
  }
  
  if (socratesData.timeCourse) {
    report += `Over time, ${socratesData.timeCourse}. `;
  }
  
  if (socratesData.exacerbatingFactors) {
    report += `Factors that affect the symptom include: ${socratesData.exacerbatingFactors}. `;
  }

  // Recommendations section
  report += `\n\nRECOMMENDATIONS FOR CLINICIAN\n`;
  report += `• Review the detailed Socrates assessment above\n`;
  report += `• Consider severity level and impact on daily activities\n`;
  report += `• Evaluate for any red flag symptoms\n`;
  report += `• Assess need for further investigations or specialist referral\n`;
  
  // Red flags section
  const severity = parseInt(socratesData.severity) || 0;
  if (severity >= 8) {
    report += `\n⚠️  HIGH SEVERITY ALERT: Patient reported severity ${severity}/10\n`;
  }

  report += `\n\nReport generated by Sympli Health Companion\n`;
  report += `For clinical use - please verify all information with the patient\n`;

  return report;
}
