import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { symptomData, socratesData } = body;

    const reportContent = generateSymptomReport(symptomData, socratesData);

    return NextResponse.json({
      reportContent
    });

  } catch (error) {
    console.error('❌ Error in generate report API:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

function generateSymptomReport(symptomData: any, socratesData: any): string {
  const now = new Date();
  const formattedDate = now.toLocaleDateString('en-GB', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  // Ensure we have valid data
  const safeSymptomData = symptomData || {};
  const safeSocratesData = socratesData || {};

  let report = `SYMPTOM REPORT\n`;
  report += `Generated: ${formattedDate}\n`;
  report += `=====================================\n\n`;

  // Basic symptom information
  report += `PRIMARY SYMPTOM\n`;
  report += `Symptom: ${safeSymptomData.symptom || 'Not specified'}\n`;
  report += `Type: ${safeSymptomData.type === 'new' ? 'New Symptom' : 'Ongoing Symptom'}\n`;
  if (safeSymptomData.description) {
    report += `Description: ${safeSymptomData.description}\n`;
  }
  report += `\n`;

  // Socrates assessment
  report += `DETAILED ASSESSMENT (SOCRATES)\n`;
  report += `Site: ${safeSocratesData.site || 'Not specified'}\n`;
  report += `Onset: ${safeSocratesData.onset || 'Not specified'}\n`;
  report += `Character: ${safeSocratesData.character || 'Not specified'}\n`;
  report += `Radiation: ${safeSocratesData.radiation || 'Not specified'}\n`;
  report += `Associations: ${safeSocratesData.associations || 'Not specified'}\n`;
  report += `Time Course: ${safeSocratesData.timeCourse || 'Not specified'}\n`;
  report += `Exacerbating Factors: ${safeSocratesData.exacerbatingFactors || 'Not specified'}\n`;
  report += `Severity: ${safeSocratesData.severity || 'Not specified'}/10\n`;
  report += `\n`;

  // Additional context
  if (safeSocratesData.additionalContext) {
    report += `ADDITIONAL CONTEXT\n`;
    report += `${safeSocratesData.additionalContext}\n`;
    report += `\n`;
  }

  // Clinical summary
  report += `CLINICAL SUMMARY\n`;
  report += `This ${safeSymptomData.type || 'unknown'} symptom of ${safeSymptomData.symptom || 'unknown'} was reported with a severity of ${safeSocratesData.severity || 'unknown'}/10. `;
  
  if (safeSocratesData.onset) {
    report += `The symptom began ${safeSocratesData.onset}. `;
  }
  
  if (safeSocratesData.character) {
    report += `It is described as ${safeSocratesData.character}. `;
  }
  
  if (safeSocratesData.timeCourse) {
    report += `Over time, ${safeSocratesData.timeCourse}. `;
  }
  
  if (safeSocratesData.exacerbatingFactors) {
    report += `Factors that affect the symptom include: ${safeSocratesData.exacerbatingFactors}. `;
  }

  // Clinical recommendations removed as requested
  
  // Red flags section
  const severity = parseInt(safeSocratesData.severity) || 0;
  if (severity >= 8) {
    report += `\n⚠️  HIGH SEVERITY ALERT: Patient reported severity ${severity}/10\n`;
  }

  report += `\n\nReport generated by Sympli Health Companion\n`;
  report += `For clinical use - please verify all information with the patient\n`;

  return report;
}
